language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - npm install

script:
  - npm run production

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build_production
  repo: mum-project/mum-project.github.io
  target-branch: master
  on:
    branches:
      only:
        - master